language: node_js
node_js:
  - "8"

deploy:
  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    env: $EB_APP_ENV
    app: $EB_APP_NAME
    region: $AWS_DEFAULT_REGION
    bucket_name: corbon-blue
