language: node_js
node_js:
  - "8"

before_deploy:
  - zip -r cordonblue_v0.0.1.zip *.js *.json public/ routes/
  - mkdir -p dpl_cd_upload
  - mv cordonblue_v0.0.1.zip dpl_cd_upload/cordonblue_v0.0.1.zip

deploy:
  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    env: $EB_APP_ENV
    app: $EB_APP_NAME
    region: $AWS_DEFAULT_REGION
    bucket_name: corbon-blue
    zip_file: dpl_cd_upload/cordonblue_v0.0.1.zip
